// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: behaviors.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Zmk_Behaviors_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestType: Zmk_Behaviors_Request.OneOf_RequestType? = nil

  var listAllBehaviors: Bool {
    get {
      if case .listAllBehaviors(let v)? = requestType {return v}
      return false
    }
    set {requestType = .listAllBehaviors(newValue)}
  }

  var getBehaviorDetails: Zmk_Behaviors_GetBehaviorDetailsRequest {
    get {
      if case .getBehaviorDetails(let v)? = requestType {return v}
      return Zmk_Behaviors_GetBehaviorDetailsRequest()
    }
    set {requestType = .getBehaviorDetails(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_RequestType: Equatable, Sendable {
    case listAllBehaviors(Bool)
    case getBehaviorDetails(Zmk_Behaviors_GetBehaviorDetailsRequest)

  }

  init() {}
}

nonisolated struct Zmk_Behaviors_GetBehaviorDetailsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var behaviorID: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var responseType: Zmk_Behaviors_Response.OneOf_ResponseType? = nil

  var listAllBehaviors: Zmk_Behaviors_ListAllBehaviorsResponse {
    get {
      if case .listAllBehaviors(let v)? = responseType {return v}
      return Zmk_Behaviors_ListAllBehaviorsResponse()
    }
    set {responseType = .listAllBehaviors(newValue)}
  }

  var getBehaviorDetails: Zmk_Behaviors_GetBehaviorDetailsResponse {
    get {
      if case .getBehaviorDetails(let v)? = responseType {return v}
      return Zmk_Behaviors_GetBehaviorDetailsResponse()
    }
    set {responseType = .getBehaviorDetails(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_ResponseType: Equatable, Sendable {
    case listAllBehaviors(Zmk_Behaviors_ListAllBehaviorsResponse)
    case getBehaviorDetails(Zmk_Behaviors_GetBehaviorDetailsResponse)

  }

  init() {}
}

nonisolated struct Zmk_Behaviors_ListAllBehaviorsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var behaviors: [UInt32] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_GetBehaviorDetailsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: UInt32 = 0

  var displayName: String = String()

  var metadata: [Zmk_Behaviors_BehaviorBindingParametersSet] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorBindingParametersSet: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var param1: [Zmk_Behaviors_BehaviorParameterValueDescription] = []

  var param2: [Zmk_Behaviors_BehaviorParameterValueDescription] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorParameterValueDescriptionRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var min: Int32 = 0

  var max: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorParameterNil: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorParameterLayerId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorParameterHidUsage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var keyboardMax: UInt32 = 0

  var consumerMax: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Behaviors_BehaviorParameterValueDescription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var valueType: Zmk_Behaviors_BehaviorParameterValueDescription.OneOf_ValueType? = nil

  var `nil`: Zmk_Behaviors_BehaviorParameterNil {
    get {
      if case .nil(let v)? = valueType {return v}
      return Zmk_Behaviors_BehaviorParameterNil()
    }
    set {valueType = .nil(newValue)}
  }

  var constant: UInt32 {
    get {
      if case .constant(let v)? = valueType {return v}
      return 0
    }
    set {valueType = .constant(newValue)}
  }

  var range: Zmk_Behaviors_BehaviorParameterValueDescriptionRange {
    get {
      if case .range(let v)? = valueType {return v}
      return Zmk_Behaviors_BehaviorParameterValueDescriptionRange()
    }
    set {valueType = .range(newValue)}
  }

  var hidUsage: Zmk_Behaviors_BehaviorParameterHidUsage {
    get {
      if case .hidUsage(let v)? = valueType {return v}
      return Zmk_Behaviors_BehaviorParameterHidUsage()
    }
    set {valueType = .hidUsage(newValue)}
  }

  var layerID: Zmk_Behaviors_BehaviorParameterLayerId {
    get {
      if case .layerID(let v)? = valueType {return v}
      return Zmk_Behaviors_BehaviorParameterLayerId()
    }
    set {valueType = .layerID(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_ValueType: Equatable, Sendable {
    case `nil`(Zmk_Behaviors_BehaviorParameterNil)
    case constant(UInt32)
    case range(Zmk_Behaviors_BehaviorParameterValueDescriptionRange)
    case hidUsage(Zmk_Behaviors_BehaviorParameterHidUsage)
    case layerID(Zmk_Behaviors_BehaviorParameterLayerId)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "zmk.behaviors"

nonisolated extension Zmk_Behaviors_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}list_all_behaviors\0\u{3}get_behavior_details\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .listAllBehaviors(v)
        }
      }()
      case 2: try {
        var v: Zmk_Behaviors_GetBehaviorDetailsRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .getBehaviorDetails(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .getBehaviorDetails(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.requestType {
    case .listAllBehaviors?: try {
      guard case .listAllBehaviors(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .getBehaviorDetails?: try {
      guard case .getBehaviorDetails(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_Request, rhs: Zmk_Behaviors_Request) -> Bool {
    if lhs.requestType != rhs.requestType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_GetBehaviorDetailsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetBehaviorDetailsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}behavior_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.behaviorID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.behaviorID != 0 {
      try visitor.visitSingularUInt32Field(value: self.behaviorID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_GetBehaviorDetailsRequest, rhs: Zmk_Behaviors_GetBehaviorDetailsRequest) -> Bool {
    if lhs.behaviorID != rhs.behaviorID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}list_all_behaviors\0\u{3}get_behavior_details\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Behaviors_ListAllBehaviorsResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .listAllBehaviors(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .listAllBehaviors(v)
        }
      }()
      case 2: try {
        var v: Zmk_Behaviors_GetBehaviorDetailsResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .getBehaviorDetails(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .getBehaviorDetails(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.responseType {
    case .listAllBehaviors?: try {
      guard case .listAllBehaviors(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getBehaviorDetails?: try {
      guard case .getBehaviorDetails(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_Response, rhs: Zmk_Behaviors_Response) -> Bool {
    if lhs.responseType != rhs.responseType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_ListAllBehaviorsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ListAllBehaviorsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}behaviors\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedUInt32Field(value: &self.behaviors) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.behaviors.isEmpty {
      try visitor.visitPackedUInt32Field(value: self.behaviors, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_ListAllBehaviorsResponse, rhs: Zmk_Behaviors_ListAllBehaviorsResponse) -> Bool {
    if lhs.behaviors != rhs.behaviors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_GetBehaviorDetailsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetBehaviorDetailsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}display_name\0\u{1}metadata\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.metadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if !self.metadata.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.metadata, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_GetBehaviorDetailsResponse, rhs: Zmk_Behaviors_GetBehaviorDetailsResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorBindingParametersSet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorBindingParametersSet"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}param1\0\u{1}param2\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.param1) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.param2) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.param1.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.param1, fieldNumber: 1)
    }
    if !self.param2.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.param2, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorBindingParametersSet, rhs: Zmk_Behaviors_BehaviorBindingParametersSet) -> Bool {
    if lhs.param1 != rhs.param1 {return false}
    if lhs.param2 != rhs.param2 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorParameterValueDescriptionRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorParameterValueDescriptionRange"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}min\0\u{1}max\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.min) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.max) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.min != 0 {
      try visitor.visitSingularInt32Field(value: self.min, fieldNumber: 1)
    }
    if self.max != 0 {
      try visitor.visitSingularInt32Field(value: self.max, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorParameterValueDescriptionRange, rhs: Zmk_Behaviors_BehaviorParameterValueDescriptionRange) -> Bool {
    if lhs.min != rhs.min {return false}
    if lhs.max != rhs.max {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorParameterNil: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorParameterNil"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorParameterNil, rhs: Zmk_Behaviors_BehaviorParameterNil) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorParameterLayerId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorParameterLayerId"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorParameterLayerId, rhs: Zmk_Behaviors_BehaviorParameterLayerId) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorParameterHidUsage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorParameterHidUsage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}keyboard_max\0\u{3}consumer_max\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.keyboardMax) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.consumerMax) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.keyboardMax != 0 {
      try visitor.visitSingularUInt32Field(value: self.keyboardMax, fieldNumber: 1)
    }
    if self.consumerMax != 0 {
      try visitor.visitSingularUInt32Field(value: self.consumerMax, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorParameterHidUsage, rhs: Zmk_Behaviors_BehaviorParameterHidUsage) -> Bool {
    if lhs.keyboardMax != rhs.keyboardMax {return false}
    if lhs.consumerMax != rhs.consumerMax {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Behaviors_BehaviorParameterValueDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorParameterValueDescription"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}nil\0\u{1}constant\0\u{1}range\0\u{3}hid_usage\0\u{3}layer_id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try {
        var v: Zmk_Behaviors_BehaviorParameterNil?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .nil(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .nil(v)
        }
      }()
      case 3: try {
        var v: UInt32?
        try decoder.decodeSingularUInt32Field(value: &v)
        if let v = v {
          if self.valueType != nil {try decoder.handleConflictingOneOf()}
          self.valueType = .constant(v)
        }
      }()
      case 4: try {
        var v: Zmk_Behaviors_BehaviorParameterValueDescriptionRange?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .range(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .range(v)
        }
      }()
      case 5: try {
        var v: Zmk_Behaviors_BehaviorParameterHidUsage?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .hidUsage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .hidUsage(v)
        }
      }()
      case 6: try {
        var v: Zmk_Behaviors_BehaviorParameterLayerId?
        var hadOneofValue = false
        if let current = self.valueType {
          hadOneofValue = true
          if case .layerID(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.valueType = .layerID(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    switch self.valueType {
    case .nil?: try {
      guard case .nil(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .constant?: try {
      guard case .constant(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    }()
    case .range?: try {
      guard case .range(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .hidUsage?: try {
      guard case .hidUsage(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .layerID?: try {
      guard case .layerID(let v)? = self.valueType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Behaviors_BehaviorParameterValueDescription, rhs: Zmk_Behaviors_BehaviorParameterValueDescription) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.valueType != rhs.valueType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
