// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: core.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Zmk_Core_LockState: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case zmkStudioCoreLockStateLocked // = 0
  case zmkStudioCoreLockStateUnlocked // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .zmkStudioCoreLockStateLocked
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .zmkStudioCoreLockStateLocked
    case 1: self = .zmkStudioCoreLockStateUnlocked
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .zmkStudioCoreLockStateLocked: return 0
    case .zmkStudioCoreLockStateUnlocked: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Core_LockState] = [
    .zmkStudioCoreLockStateLocked,
    .zmkStudioCoreLockStateUnlocked,
  ]

}

nonisolated struct Zmk_Core_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestType: Zmk_Core_Request.OneOf_RequestType? = nil

  var getDeviceInfo: Bool {
    get {
      if case .getDeviceInfo(let v)? = requestType {return v}
      return false
    }
    set {requestType = .getDeviceInfo(newValue)}
  }

  var getLockState: Bool {
    get {
      if case .getLockState(let v)? = requestType {return v}
      return false
    }
    set {requestType = .getLockState(newValue)}
  }

  var lock: Bool {
    get {
      if case .lock(let v)? = requestType {return v}
      return false
    }
    set {requestType = .lock(newValue)}
  }

  var resetSettings: Bool {
    get {
      if case .resetSettings(let v)? = requestType {return v}
      return false
    }
    set {requestType = .resetSettings(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_RequestType: Equatable, Sendable {
    case getDeviceInfo(Bool)
    case getLockState(Bool)
    case lock(Bool)
    case resetSettings(Bool)

  }

  init() {}
}

nonisolated struct Zmk_Core_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var responseType: Zmk_Core_Response.OneOf_ResponseType? = nil

  var getDeviceInfo: Zmk_Core_GetDeviceInfoResponse {
    get {
      if case .getDeviceInfo(let v)? = responseType {return v}
      return Zmk_Core_GetDeviceInfoResponse()
    }
    set {responseType = .getDeviceInfo(newValue)}
  }

  var getLockState: Zmk_Core_LockState {
    get {
      if case .getLockState(let v)? = responseType {return v}
      return .zmkStudioCoreLockStateLocked
    }
    set {responseType = .getLockState(newValue)}
  }

  var resetSettings: Bool {
    get {
      if case .resetSettings(let v)? = responseType {return v}
      return false
    }
    set {responseType = .resetSettings(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_ResponseType: Equatable, Sendable {
    case getDeviceInfo(Zmk_Core_GetDeviceInfoResponse)
    case getLockState(Zmk_Core_LockState)
    case resetSettings(Bool)

  }

  init() {}
}

nonisolated struct Zmk_Core_GetDeviceInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var serialNumber: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Core_Notification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var notificationType: Zmk_Core_Notification.OneOf_NotificationType? = nil

  var lockStateChanged: Zmk_Core_LockState {
    get {
      if case .lockStateChanged(let v)? = notificationType {return v}
      return .zmkStudioCoreLockStateLocked
    }
    set {notificationType = .lockStateChanged(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_NotificationType: Equatable, Sendable {
    case lockStateChanged(Zmk_Core_LockState)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "zmk.core"

nonisolated extension Zmk_Core_LockState: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ZMK_STUDIO_CORE_LOCK_STATE_LOCKED\0\u{1}ZMK_STUDIO_CORE_LOCK_STATE_UNLOCKED\0")
}

nonisolated extension Zmk_Core_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_device_info\0\u{3}get_lock_state\0\u{1}lock\0\u{3}reset_settings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .getDeviceInfo(v)
        }
      }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .getLockState(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .lock(v)
        }
      }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .resetSettings(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.requestType {
    case .getDeviceInfo?: try {
      guard case .getDeviceInfo(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .getLockState?: try {
      guard case .getLockState(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case .lock?: try {
      guard case .lock(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .resetSettings?: try {
      guard case .resetSettings(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Core_Request, rhs: Zmk_Core_Request) -> Bool {
    if lhs.requestType != rhs.requestType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Core_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_device_info\0\u{3}get_lock_state\0\u{4}\u{2}reset_settings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Core_GetDeviceInfoResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .getDeviceInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .getDeviceInfo(v)
        }
      }()
      case 2: try {
        var v: Zmk_Core_LockState?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .getLockState(v)
        }
      }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .resetSettings(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.responseType {
    case .getDeviceInfo?: try {
      guard case .getDeviceInfo(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getLockState?: try {
      guard case .getLockState(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case .resetSettings?: try {
      guard case .resetSettings(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Core_Response, rhs: Zmk_Core_Response) -> Bool {
    if lhs.responseType != rhs.responseType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Core_GetDeviceInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetDeviceInfoResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}serial_number\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.serialNumber) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.serialNumber.isEmpty {
      try visitor.visitSingularBytesField(value: self.serialNumber, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Core_GetDeviceInfoResponse, rhs: Zmk_Core_GetDeviceInfoResponse) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.serialNumber != rhs.serialNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Core_Notification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Notification"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}lock_state_changed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Core_LockState?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.notificationType != nil {try decoder.handleConflictingOneOf()}
          self.notificationType = .lockStateChanged(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .lockStateChanged(let v)? = self.notificationType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Core_Notification, rhs: Zmk_Core_Notification) -> Bool {
    if lhs.notificationType != rhs.notificationType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
