// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: keymap.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Zmk_Keymap_SaveChangesErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case saveChangesErrOk // = 0
  case saveChangesErrGeneric // = 1
  case saveChangesErrNotSupported // = 2
  case saveChangesErrNoSpace // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .saveChangesErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .saveChangesErrOk
    case 1: self = .saveChangesErrGeneric
    case 2: self = .saveChangesErrNotSupported
    case 3: self = .saveChangesErrNoSpace
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .saveChangesErrOk: return 0
    case .saveChangesErrGeneric: return 1
    case .saveChangesErrNotSupported: return 2
    case .saveChangesErrNoSpace: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_SaveChangesErrorCode] = [
    .saveChangesErrOk,
    .saveChangesErrGeneric,
    .saveChangesErrNotSupported,
    .saveChangesErrNoSpace,
  ]

}

nonisolated enum Zmk_Keymap_SetLayerBindingResponse: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case setLayerBindingRespOk // = 0
  case setLayerBindingRespInvalidLocation // = 1
  case setLayerBindingRespInvalidBehavior // = 2
  case setLayerBindingRespInvalidParameters // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .setLayerBindingRespOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .setLayerBindingRespOk
    case 1: self = .setLayerBindingRespInvalidLocation
    case 2: self = .setLayerBindingRespInvalidBehavior
    case 3: self = .setLayerBindingRespInvalidParameters
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .setLayerBindingRespOk: return 0
    case .setLayerBindingRespInvalidLocation: return 1
    case .setLayerBindingRespInvalidBehavior: return 2
    case .setLayerBindingRespInvalidParameters: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_SetLayerBindingResponse] = [
    .setLayerBindingRespOk,
    .setLayerBindingRespInvalidLocation,
    .setLayerBindingRespInvalidBehavior,
    .setLayerBindingRespInvalidParameters,
  ]

}

nonisolated enum Zmk_Keymap_MoveLayerErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case moveLayerErrOk // = 0
  case moveLayerErrGeneric // = 1
  case moveLayerErrInvalidLayer // = 2
  case moveLayerErrInvalidDestination // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .moveLayerErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .moveLayerErrOk
    case 1: self = .moveLayerErrGeneric
    case 2: self = .moveLayerErrInvalidLayer
    case 3: self = .moveLayerErrInvalidDestination
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .moveLayerErrOk: return 0
    case .moveLayerErrGeneric: return 1
    case .moveLayerErrInvalidLayer: return 2
    case .moveLayerErrInvalidDestination: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_MoveLayerErrorCode] = [
    .moveLayerErrOk,
    .moveLayerErrGeneric,
    .moveLayerErrInvalidLayer,
    .moveLayerErrInvalidDestination,
  ]

}

nonisolated enum Zmk_Keymap_AddLayerErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case addLayerErrOk // = 0
  case addLayerErrGeneric // = 1
  case addLayerErrNoSpace // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .addLayerErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .addLayerErrOk
    case 1: self = .addLayerErrGeneric
    case 2: self = .addLayerErrNoSpace
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .addLayerErrOk: return 0
    case .addLayerErrGeneric: return 1
    case .addLayerErrNoSpace: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_AddLayerErrorCode] = [
    .addLayerErrOk,
    .addLayerErrGeneric,
    .addLayerErrNoSpace,
  ]

}

nonisolated enum Zmk_Keymap_RemoveLayerErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case removeLayerErrOk // = 0
  case removeLayerErrGeneric // = 1
  case removeLayerErrInvalidIndex // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .removeLayerErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .removeLayerErrOk
    case 1: self = .removeLayerErrGeneric
    case 2: self = .removeLayerErrInvalidIndex
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .removeLayerErrOk: return 0
    case .removeLayerErrGeneric: return 1
    case .removeLayerErrInvalidIndex: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_RemoveLayerErrorCode] = [
    .removeLayerErrOk,
    .removeLayerErrGeneric,
    .removeLayerErrInvalidIndex,
  ]

}

nonisolated enum Zmk_Keymap_RestoreLayerErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case restoreLayerErrOk // = 0
  case restoreLayerErrGeneric // = 1
  case restoreLayerErrInvalidID // = 2
  case restoreLayerErrInvalidIndex // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .restoreLayerErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .restoreLayerErrOk
    case 1: self = .restoreLayerErrGeneric
    case 2: self = .restoreLayerErrInvalidID
    case 3: self = .restoreLayerErrInvalidIndex
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .restoreLayerErrOk: return 0
    case .restoreLayerErrGeneric: return 1
    case .restoreLayerErrInvalidID: return 2
    case .restoreLayerErrInvalidIndex: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_RestoreLayerErrorCode] = [
    .restoreLayerErrOk,
    .restoreLayerErrGeneric,
    .restoreLayerErrInvalidID,
    .restoreLayerErrInvalidIndex,
  ]

}

nonisolated enum Zmk_Keymap_SetLayerPropsResponse: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case setLayerPropsRespOk // = 0
  case setLayerPropsRespErrGeneric // = 1
  case setLayerPropsRespErrInvalidID // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .setLayerPropsRespOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .setLayerPropsRespOk
    case 1: self = .setLayerPropsRespErrGeneric
    case 2: self = .setLayerPropsRespErrInvalidID
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .setLayerPropsRespOk: return 0
    case .setLayerPropsRespErrGeneric: return 1
    case .setLayerPropsRespErrInvalidID: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_SetLayerPropsResponse] = [
    .setLayerPropsRespOk,
    .setLayerPropsRespErrGeneric,
    .setLayerPropsRespErrInvalidID,
  ]

}

nonisolated enum Zmk_Keymap_SetActivePhysicalLayoutErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case setActivePhysicalLayoutErrOk // = 0
  case setActivePhysicalLayoutErrGeneric // = 1
  case setActivePhysicalLayoutErrInvalidLayoutIndex // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .setActivePhysicalLayoutErrOk
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .setActivePhysicalLayoutErrOk
    case 1: self = .setActivePhysicalLayoutErrGeneric
    case 2: self = .setActivePhysicalLayoutErrInvalidLayoutIndex
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .setActivePhysicalLayoutErrOk: return 0
    case .setActivePhysicalLayoutErrGeneric: return 1
    case .setActivePhysicalLayoutErrInvalidLayoutIndex: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Keymap_SetActivePhysicalLayoutErrorCode] = [
    .setActivePhysicalLayoutErrOk,
    .setActivePhysicalLayoutErrGeneric,
    .setActivePhysicalLayoutErrInvalidLayoutIndex,
  ]

}

nonisolated struct Zmk_Keymap_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestType: Zmk_Keymap_Request.OneOf_RequestType? = nil

  var getKeymap: Bool {
    get {
      if case .getKeymap(let v)? = requestType {return v}
      return false
    }
    set {requestType = .getKeymap(newValue)}
  }

  var setLayerBinding: Zmk_Keymap_SetLayerBindingRequest {
    get {
      if case .setLayerBinding(let v)? = requestType {return v}
      return Zmk_Keymap_SetLayerBindingRequest()
    }
    set {requestType = .setLayerBinding(newValue)}
  }

  var checkUnsavedChanges: Bool {
    get {
      if case .checkUnsavedChanges(let v)? = requestType {return v}
      return false
    }
    set {requestType = .checkUnsavedChanges(newValue)}
  }

  var saveChanges: Bool {
    get {
      if case .saveChanges(let v)? = requestType {return v}
      return false
    }
    set {requestType = .saveChanges(newValue)}
  }

  var discardChanges: Bool {
    get {
      if case .discardChanges(let v)? = requestType {return v}
      return false
    }
    set {requestType = .discardChanges(newValue)}
  }

  var getPhysicalLayouts: Bool {
    get {
      if case .getPhysicalLayouts(let v)? = requestType {return v}
      return false
    }
    set {requestType = .getPhysicalLayouts(newValue)}
  }

  var setActivePhysicalLayout: UInt32 {
    get {
      if case .setActivePhysicalLayout(let v)? = requestType {return v}
      return 0
    }
    set {requestType = .setActivePhysicalLayout(newValue)}
  }

  var moveLayer: Zmk_Keymap_MoveLayerRequest {
    get {
      if case .moveLayer(let v)? = requestType {return v}
      return Zmk_Keymap_MoveLayerRequest()
    }
    set {requestType = .moveLayer(newValue)}
  }

  var addLayer: Zmk_Keymap_AddLayerRequest {
    get {
      if case .addLayer(let v)? = requestType {return v}
      return Zmk_Keymap_AddLayerRequest()
    }
    set {requestType = .addLayer(newValue)}
  }

  var removeLayer: Zmk_Keymap_RemoveLayerRequest {
    get {
      if case .removeLayer(let v)? = requestType {return v}
      return Zmk_Keymap_RemoveLayerRequest()
    }
    set {requestType = .removeLayer(newValue)}
  }

  var restoreLayer: Zmk_Keymap_RestoreLayerRequest {
    get {
      if case .restoreLayer(let v)? = requestType {return v}
      return Zmk_Keymap_RestoreLayerRequest()
    }
    set {requestType = .restoreLayer(newValue)}
  }

  var setLayerProps: Zmk_Keymap_SetLayerPropsRequest {
    get {
      if case .setLayerProps(let v)? = requestType {return v}
      return Zmk_Keymap_SetLayerPropsRequest()
    }
    set {requestType = .setLayerProps(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_RequestType: Equatable, Sendable {
    case getKeymap(Bool)
    case setLayerBinding(Zmk_Keymap_SetLayerBindingRequest)
    case checkUnsavedChanges(Bool)
    case saveChanges(Bool)
    case discardChanges(Bool)
    case getPhysicalLayouts(Bool)
    case setActivePhysicalLayout(UInt32)
    case moveLayer(Zmk_Keymap_MoveLayerRequest)
    case addLayer(Zmk_Keymap_AddLayerRequest)
    case removeLayer(Zmk_Keymap_RemoveLayerRequest)
    case restoreLayer(Zmk_Keymap_RestoreLayerRequest)
    case setLayerProps(Zmk_Keymap_SetLayerPropsRequest)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var responseType: Zmk_Keymap_Response.OneOf_ResponseType? = nil

  var getKeymap: Zmk_Keymap_Keymap {
    get {
      if case .getKeymap(let v)? = responseType {return v}
      return Zmk_Keymap_Keymap()
    }
    set {responseType = .getKeymap(newValue)}
  }

  var setLayerBinding: Zmk_Keymap_SetLayerBindingResponse {
    get {
      if case .setLayerBinding(let v)? = responseType {return v}
      return .setLayerBindingRespOk
    }
    set {responseType = .setLayerBinding(newValue)}
  }

  var checkUnsavedChanges: Bool {
    get {
      if case .checkUnsavedChanges(let v)? = responseType {return v}
      return false
    }
    set {responseType = .checkUnsavedChanges(newValue)}
  }

  var saveChanges: Zmk_Keymap_SaveChangesResponse {
    get {
      if case .saveChanges(let v)? = responseType {return v}
      return Zmk_Keymap_SaveChangesResponse()
    }
    set {responseType = .saveChanges(newValue)}
  }

  var discardChanges: Bool {
    get {
      if case .discardChanges(let v)? = responseType {return v}
      return false
    }
    set {responseType = .discardChanges(newValue)}
  }

  var getPhysicalLayouts: Zmk_Keymap_PhysicalLayouts {
    get {
      if case .getPhysicalLayouts(let v)? = responseType {return v}
      return Zmk_Keymap_PhysicalLayouts()
    }
    set {responseType = .getPhysicalLayouts(newValue)}
  }

  var setActivePhysicalLayout: Zmk_Keymap_SetActivePhysicalLayoutResponse {
    get {
      if case .setActivePhysicalLayout(let v)? = responseType {return v}
      return Zmk_Keymap_SetActivePhysicalLayoutResponse()
    }
    set {responseType = .setActivePhysicalLayout(newValue)}
  }

  var moveLayer: Zmk_Keymap_MoveLayerResponse {
    get {
      if case .moveLayer(let v)? = responseType {return v}
      return Zmk_Keymap_MoveLayerResponse()
    }
    set {responseType = .moveLayer(newValue)}
  }

  var addLayer: Zmk_Keymap_AddLayerResponse {
    get {
      if case .addLayer(let v)? = responseType {return v}
      return Zmk_Keymap_AddLayerResponse()
    }
    set {responseType = .addLayer(newValue)}
  }

  var removeLayer: Zmk_Keymap_RemoveLayerResponse {
    get {
      if case .removeLayer(let v)? = responseType {return v}
      return Zmk_Keymap_RemoveLayerResponse()
    }
    set {responseType = .removeLayer(newValue)}
  }

  var restoreLayer: Zmk_Keymap_RestoreLayerResponse {
    get {
      if case .restoreLayer(let v)? = responseType {return v}
      return Zmk_Keymap_RestoreLayerResponse()
    }
    set {responseType = .restoreLayer(newValue)}
  }

  var setLayerProps: Zmk_Keymap_SetLayerPropsResponse {
    get {
      if case .setLayerProps(let v)? = responseType {return v}
      return .setLayerPropsRespOk
    }
    set {responseType = .setLayerProps(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_ResponseType: Equatable, Sendable {
    case getKeymap(Zmk_Keymap_Keymap)
    case setLayerBinding(Zmk_Keymap_SetLayerBindingResponse)
    case checkUnsavedChanges(Bool)
    case saveChanges(Zmk_Keymap_SaveChangesResponse)
    case discardChanges(Bool)
    case getPhysicalLayouts(Zmk_Keymap_PhysicalLayouts)
    case setActivePhysicalLayout(Zmk_Keymap_SetActivePhysicalLayoutResponse)
    case moveLayer(Zmk_Keymap_MoveLayerResponse)
    case addLayer(Zmk_Keymap_AddLayerResponse)
    case removeLayer(Zmk_Keymap_RemoveLayerResponse)
    case restoreLayer(Zmk_Keymap_RestoreLayerResponse)
    case setLayerProps(Zmk_Keymap_SetLayerPropsResponse)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_Notification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var notificationType: Zmk_Keymap_Notification.OneOf_NotificationType? = nil

  var unsavedChangesStatusChanged: Bool {
    get {
      if case .unsavedChangesStatusChanged(let v)? = notificationType {return v}
      return false
    }
    set {notificationType = .unsavedChangesStatusChanged(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_NotificationType: Equatable, Sendable {
    case unsavedChangesStatusChanged(Bool)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_SaveChangesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_SaveChangesResponse.OneOf_Result? = nil

  var ok: Bool {
    get {
      if case .ok(let v)? = result {return v}
      return false
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_SaveChangesErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .saveChangesErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Bool)
    case err(Zmk_Keymap_SaveChangesErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_SetActivePhysicalLayoutResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_SetActivePhysicalLayoutResponse.OneOf_Result? = nil

  var ok: Zmk_Keymap_Keymap {
    get {
      if case .ok(let v)? = result {return v}
      return Zmk_Keymap_Keymap()
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_SetActivePhysicalLayoutErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .setActivePhysicalLayoutErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Zmk_Keymap_Keymap)
    case err(Zmk_Keymap_SetActivePhysicalLayoutErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_MoveLayerResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_MoveLayerResponse.OneOf_Result? = nil

  var ok: Zmk_Keymap_Keymap {
    get {
      if case .ok(let v)? = result {return v}
      return Zmk_Keymap_Keymap()
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_MoveLayerErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .moveLayerErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Zmk_Keymap_Keymap)
    case err(Zmk_Keymap_MoveLayerErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_AddLayerResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_AddLayerResponse.OneOf_Result? = nil

  var ok: Zmk_Keymap_AddLayerResponseDetails {
    get {
      if case .ok(let v)? = result {return v}
      return Zmk_Keymap_AddLayerResponseDetails()
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_AddLayerErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .addLayerErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Zmk_Keymap_AddLayerResponseDetails)
    case err(Zmk_Keymap_AddLayerErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_AddLayerResponseDetails: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var index: UInt32 = 0

  var layer: Zmk_Keymap_Layer {
    get {_layer ?? Zmk_Keymap_Layer()}
    set {_layer = newValue}
  }
  /// Returns true if `layer` has been explicitly set.
  var hasLayer: Bool {self._layer != nil}
  /// Clears the value of `layer`. Subsequent reads from it will return its default value.
  mutating func clearLayer() {self._layer = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _layer: Zmk_Keymap_Layer? = nil
}

nonisolated struct Zmk_Keymap_RemoveLayerResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_RemoveLayerResponse.OneOf_Result? = nil

  var ok: Zmk_Keymap_RemoveLayerOk {
    get {
      if case .ok(let v)? = result {return v}
      return Zmk_Keymap_RemoveLayerOk()
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_RemoveLayerErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .removeLayerErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Zmk_Keymap_RemoveLayerOk)
    case err(Zmk_Keymap_RemoveLayerErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_RemoveLayerOk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_RestoreLayerResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var result: Zmk_Keymap_RestoreLayerResponse.OneOf_Result? = nil

  var ok: Zmk_Keymap_Layer {
    get {
      if case .ok(let v)? = result {return v}
      return Zmk_Keymap_Layer()
    }
    set {result = .ok(newValue)}
  }

  var err: Zmk_Keymap_RestoreLayerErrorCode {
    get {
      if case .err(let v)? = result {return v}
      return .restoreLayerErrOk
    }
    set {result = .err(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Result: Equatable, Sendable {
    case ok(Zmk_Keymap_Layer)
    case err(Zmk_Keymap_RestoreLayerErrorCode)

  }

  init() {}
}

nonisolated struct Zmk_Keymap_SetLayerBindingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var layerID: UInt32 = 0

  var keyPosition: Int32 = 0

  var binding: Zmk_Keymap_BehaviorBinding {
    get {_binding ?? Zmk_Keymap_BehaviorBinding()}
    set {_binding = newValue}
  }
  /// Returns true if `binding` has been explicitly set.
  var hasBinding: Bool {self._binding != nil}
  /// Clears the value of `binding`. Subsequent reads from it will return its default value.
  mutating func clearBinding() {self._binding = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _binding: Zmk_Keymap_BehaviorBinding? = nil
}

nonisolated struct Zmk_Keymap_MoveLayerRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var startIndex: UInt32 = 0

  var destIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_AddLayerRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_RemoveLayerRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var layerIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_RestoreLayerRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var layerID: UInt32 = 0

  var atIndex: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_SetLayerPropsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var layerID: UInt32 = 0

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_Keymap: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var layers: [Zmk_Keymap_Layer] = []

  var availableLayers: UInt32 = 0

  var maxLayerNameLength: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_Layer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: UInt32 = 0

  var name: String = String()

  var bindings: [Zmk_Keymap_BehaviorBinding] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_BehaviorBinding: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var behaviorID: Int32 = 0

  var param1: UInt32 = 0

  var param2: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_PhysicalLayouts: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activeLayoutIndex: UInt32 = 0

  var layouts: [Zmk_Keymap_PhysicalLayout] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_PhysicalLayout: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var keys: [Zmk_Keymap_KeyPhysicalAttrs] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Zmk_Keymap_KeyPhysicalAttrs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var width: Int32 = 0

  var height: Int32 = 0

  var x: Int32 = 0

  var y: Int32 = 0

  var r: Int32 = 0

  var rx: Int32 = 0

  var ry: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "zmk.keymap"

nonisolated extension Zmk_Keymap_SaveChangesErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SAVE_CHANGES_ERR_OK\0\u{1}SAVE_CHANGES_ERR_GENERIC\0\u{1}SAVE_CHANGES_ERR_NOT_SUPPORTED\0\u{1}SAVE_CHANGES_ERR_NO_SPACE\0")
}

nonisolated extension Zmk_Keymap_SetLayerBindingResponse: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SET_LAYER_BINDING_RESP_OK\0\u{1}SET_LAYER_BINDING_RESP_INVALID_LOCATION\0\u{1}SET_LAYER_BINDING_RESP_INVALID_BEHAVIOR\0\u{1}SET_LAYER_BINDING_RESP_INVALID_PARAMETERS\0")
}

nonisolated extension Zmk_Keymap_MoveLayerErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MOVE_LAYER_ERR_OK\0\u{1}MOVE_LAYER_ERR_GENERIC\0\u{1}MOVE_LAYER_ERR_INVALID_LAYER\0\u{1}MOVE_LAYER_ERR_INVALID_DESTINATION\0")
}

nonisolated extension Zmk_Keymap_AddLayerErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ADD_LAYER_ERR_OK\0\u{1}ADD_LAYER_ERR_GENERIC\0\u{1}ADD_LAYER_ERR_NO_SPACE\0")
}

nonisolated extension Zmk_Keymap_RemoveLayerErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REMOVE_LAYER_ERR_OK\0\u{1}REMOVE_LAYER_ERR_GENERIC\0\u{1}REMOVE_LAYER_ERR_INVALID_INDEX\0")
}

nonisolated extension Zmk_Keymap_RestoreLayerErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0RESTORE_LAYER_ERR_OK\0\u{1}RESTORE_LAYER_ERR_GENERIC\0\u{1}RESTORE_LAYER_ERR_INVALID_ID\0\u{1}RESTORE_LAYER_ERR_INVALID_INDEX\0")
}

nonisolated extension Zmk_Keymap_SetLayerPropsResponse: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SET_LAYER_PROPS_RESP_OK\0\u{1}SET_LAYER_PROPS_RESP_ERR_GENERIC\0\u{1}SET_LAYER_PROPS_RESP_ERR_INVALID_ID\0")
}

nonisolated extension Zmk_Keymap_SetActivePhysicalLayoutErrorCode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SET_ACTIVE_PHYSICAL_LAYOUT_ERR_OK\0\u{1}SET_ACTIVE_PHYSICAL_LAYOUT_ERR_GENERIC\0\u{1}SET_ACTIVE_PHYSICAL_LAYOUT_ERR_INVALID_LAYOUT_INDEX\0")
}

nonisolated extension Zmk_Keymap_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_keymap\0\u{3}set_layer_binding\0\u{3}check_unsaved_changes\0\u{3}save_changes\0\u{3}discard_changes\0\u{3}get_physical_layouts\0\u{3}set_active_physical_layout\0\u{3}move_layer\0\u{3}add_layer\0\u{3}remove_layer\0\u{3}restore_layer\0\u{3}set_layer_props\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .getKeymap(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_SetLayerBindingRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .setLayerBinding(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .setLayerBinding(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .checkUnsavedChanges(v)
        }
      }()
      case 4: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .saveChanges(v)
        }
      }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .discardChanges(v)
        }
      }()
      case 6: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .getPhysicalLayouts(v)
        }
      }()
      case 7: try {
        var v: UInt32?
        try decoder.decodeSingularUInt32Field(value: &v)
        if let v = v {
          if self.requestType != nil {try decoder.handleConflictingOneOf()}
          self.requestType = .setActivePhysicalLayout(v)
        }
      }()
      case 8: try {
        var v: Zmk_Keymap_MoveLayerRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .moveLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .moveLayer(v)
        }
      }()
      case 9: try {
        var v: Zmk_Keymap_AddLayerRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .addLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .addLayer(v)
        }
      }()
      case 10: try {
        var v: Zmk_Keymap_RemoveLayerRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .removeLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .removeLayer(v)
        }
      }()
      case 11: try {
        var v: Zmk_Keymap_RestoreLayerRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .restoreLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .restoreLayer(v)
        }
      }()
      case 12: try {
        var v: Zmk_Keymap_SetLayerPropsRequest?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .setLayerProps(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .setLayerProps(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.requestType {
    case .getKeymap?: try {
      guard case .getKeymap(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .setLayerBinding?: try {
      guard case .setLayerBinding(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .checkUnsavedChanges?: try {
      guard case .checkUnsavedChanges(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .saveChanges?: try {
      guard case .saveChanges(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    }()
    case .discardChanges?: try {
      guard case .discardChanges(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case .getPhysicalLayouts?: try {
      guard case .getPhysicalLayouts(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    }()
    case .setActivePhysicalLayout?: try {
      guard case .setActivePhysicalLayout(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    }()
    case .moveLayer?: try {
      guard case .moveLayer(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .addLayer?: try {
      guard case .addLayer(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .removeLayer?: try {
      guard case .removeLayer(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .restoreLayer?: try {
      guard case .restoreLayer(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .setLayerProps?: try {
      guard case .setLayerProps(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_Request, rhs: Zmk_Keymap_Request) -> Bool {
    if lhs.requestType != rhs.requestType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_keymap\0\u{3}set_layer_binding\0\u{3}check_unsaved_changes\0\u{3}save_changes\0\u{3}discard_changes\0\u{3}get_physical_layouts\0\u{3}set_active_physical_layout\0\u{3}move_layer\0\u{3}add_layer\0\u{3}remove_layer\0\u{3}restore_layer\0\u{3}set_layer_props\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_Keymap?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .getKeymap(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .getKeymap(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_SetLayerBindingResponse?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .setLayerBinding(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .checkUnsavedChanges(v)
        }
      }()
      case 4: try {
        var v: Zmk_Keymap_SaveChangesResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .saveChanges(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .saveChanges(v)
        }
      }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .discardChanges(v)
        }
      }()
      case 6: try {
        var v: Zmk_Keymap_PhysicalLayouts?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .getPhysicalLayouts(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .getPhysicalLayouts(v)
        }
      }()
      case 7: try {
        var v: Zmk_Keymap_SetActivePhysicalLayoutResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .setActivePhysicalLayout(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .setActivePhysicalLayout(v)
        }
      }()
      case 8: try {
        var v: Zmk_Keymap_MoveLayerResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .moveLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .moveLayer(v)
        }
      }()
      case 9: try {
        var v: Zmk_Keymap_AddLayerResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .addLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .addLayer(v)
        }
      }()
      case 10: try {
        var v: Zmk_Keymap_RemoveLayerResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .removeLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .removeLayer(v)
        }
      }()
      case 11: try {
        var v: Zmk_Keymap_RestoreLayerResponse?
        var hadOneofValue = false
        if let current = self.responseType {
          hadOneofValue = true
          if case .restoreLayer(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.responseType = .restoreLayer(v)
        }
      }()
      case 12: try {
        var v: Zmk_Keymap_SetLayerPropsResponse?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .setLayerProps(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.responseType {
    case .getKeymap?: try {
      guard case .getKeymap(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .setLayerBinding?: try {
      guard case .setLayerBinding(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case .checkUnsavedChanges?: try {
      guard case .checkUnsavedChanges(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .saveChanges?: try {
      guard case .saveChanges(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .discardChanges?: try {
      guard case .discardChanges(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case .getPhysicalLayouts?: try {
      guard case .getPhysicalLayouts(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .setActivePhysicalLayout?: try {
      guard case .setActivePhysicalLayout(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .moveLayer?: try {
      guard case .moveLayer(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case .addLayer?: try {
      guard case .addLayer(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    }()
    case .removeLayer?: try {
      guard case .removeLayer(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .restoreLayer?: try {
      guard case .restoreLayer(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .setLayerProps?: try {
      guard case .setLayerProps(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_Response, rhs: Zmk_Keymap_Response) -> Bool {
    if lhs.responseType != rhs.responseType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_Notification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Notification"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}unsaved_changes_status_changed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.notificationType != nil {try decoder.handleConflictingOneOf()}
          self.notificationType = .unsavedChangesStatusChanged(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .unsavedChangesStatusChanged(let v)? = self.notificationType {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_Notification, rhs: Zmk_Keymap_Notification) -> Bool {
    if lhs.notificationType != rhs.notificationType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_SaveChangesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SaveChangesResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_SaveChangesErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_SaveChangesResponse, rhs: Zmk_Keymap_SaveChangesResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_SetActivePhysicalLayoutResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetActivePhysicalLayoutResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_Keymap?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .ok(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_SetActivePhysicalLayoutErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_SetActivePhysicalLayoutResponse, rhs: Zmk_Keymap_SetActivePhysicalLayoutResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_MoveLayerResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MoveLayerResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_Keymap?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .ok(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_MoveLayerErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_MoveLayerResponse, rhs: Zmk_Keymap_MoveLayerResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_AddLayerResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddLayerResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_AddLayerResponseDetails?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .ok(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_AddLayerErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_AddLayerResponse, rhs: Zmk_Keymap_AddLayerResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_AddLayerResponseDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddLayerResponseDetails"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}index\0\u{1}layer\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._layer) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.index != 0 {
      try visitor.visitSingularUInt32Field(value: self.index, fieldNumber: 1)
    }
    try { if let v = self._layer {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_AddLayerResponseDetails, rhs: Zmk_Keymap_AddLayerResponseDetails) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs._layer != rhs._layer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_RemoveLayerResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RemoveLayerResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_RemoveLayerOk?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .ok(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_RemoveLayerErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_RemoveLayerResponse, rhs: Zmk_Keymap_RemoveLayerResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_RemoveLayerOk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RemoveLayerOk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_RemoveLayerOk, rhs: Zmk_Keymap_RemoveLayerOk) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_RestoreLayerResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RestoreLayerResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ok\0\u{1}err\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Keymap_Layer?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .ok(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .ok(v)
        }
      }()
      case 2: try {
        var v: Zmk_Keymap_RestoreLayerErrorCode?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.result != nil {try decoder.handleConflictingOneOf()}
          self.result = .err(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.result {
    case .ok?: try {
      guard case .ok(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .err?: try {
      guard case .err(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_RestoreLayerResponse, rhs: Zmk_Keymap_RestoreLayerResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_SetLayerBindingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetLayerBindingRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}layer_id\0\u{3}key_position\0\u{1}binding\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.layerID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.keyPosition) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._binding) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.layerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.layerID, fieldNumber: 1)
    }
    if self.keyPosition != 0 {
      try visitor.visitSingularInt32Field(value: self.keyPosition, fieldNumber: 2)
    }
    try { if let v = self._binding {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_SetLayerBindingRequest, rhs: Zmk_Keymap_SetLayerBindingRequest) -> Bool {
    if lhs.layerID != rhs.layerID {return false}
    if lhs.keyPosition != rhs.keyPosition {return false}
    if lhs._binding != rhs._binding {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_MoveLayerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MoveLayerRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_index\0\u{3}dest_index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.startIndex) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.destIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.startIndex, fieldNumber: 1)
    }
    if self.destIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.destIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_MoveLayerRequest, rhs: Zmk_Keymap_MoveLayerRequest) -> Bool {
    if lhs.startIndex != rhs.startIndex {return false}
    if lhs.destIndex != rhs.destIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_AddLayerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddLayerRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_AddLayerRequest, rhs: Zmk_Keymap_AddLayerRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_RemoveLayerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RemoveLayerRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}layer_index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.layerIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.layerIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.layerIndex, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_RemoveLayerRequest, rhs: Zmk_Keymap_RemoveLayerRequest) -> Bool {
    if lhs.layerIndex != rhs.layerIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_RestoreLayerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RestoreLayerRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}layer_id\0\u{3}at_index\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.layerID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.atIndex) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.layerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.layerID, fieldNumber: 1)
    }
    if self.atIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.atIndex, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_RestoreLayerRequest, rhs: Zmk_Keymap_RestoreLayerRequest) -> Bool {
    if lhs.layerID != rhs.layerID {return false}
    if lhs.atIndex != rhs.atIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_SetLayerPropsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SetLayerPropsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}layer_id\0\u{1}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.layerID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.layerID != 0 {
      try visitor.visitSingularUInt32Field(value: self.layerID, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_SetLayerPropsRequest, rhs: Zmk_Keymap_SetLayerPropsRequest) -> Bool {
    if lhs.layerID != rhs.layerID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_Keymap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Keymap"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}layers\0\u{3}available_layers\0\u{3}max_layer_name_length\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.layers) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.availableLayers) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.maxLayerNameLength) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.layers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.layers, fieldNumber: 1)
    }
    if self.availableLayers != 0 {
      try visitor.visitSingularUInt32Field(value: self.availableLayers, fieldNumber: 2)
    }
    if self.maxLayerNameLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxLayerNameLength, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_Keymap, rhs: Zmk_Keymap_Keymap) -> Bool {
    if lhs.layers != rhs.layers {return false}
    if lhs.availableLayers != rhs.availableLayers {return false}
    if lhs.maxLayerNameLength != rhs.maxLayerNameLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_Layer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Layer"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}bindings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.bindings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.bindings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.bindings, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_Layer, rhs: Zmk_Keymap_Layer) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.bindings != rhs.bindings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_BehaviorBinding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BehaviorBinding"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}behavior_id\0\u{1}param1\0\u{1}param2\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.behaviorID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.param1) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.param2) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.behaviorID != 0 {
      try visitor.visitSingularSInt32Field(value: self.behaviorID, fieldNumber: 1)
    }
    if self.param1 != 0 {
      try visitor.visitSingularUInt32Field(value: self.param1, fieldNumber: 2)
    }
    if self.param2 != 0 {
      try visitor.visitSingularUInt32Field(value: self.param2, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_BehaviorBinding, rhs: Zmk_Keymap_BehaviorBinding) -> Bool {
    if lhs.behaviorID != rhs.behaviorID {return false}
    if lhs.param1 != rhs.param1 {return false}
    if lhs.param2 != rhs.param2 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_PhysicalLayouts: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PhysicalLayouts"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}active_layout_index\0\u{1}layouts\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.activeLayoutIndex) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.layouts) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.activeLayoutIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.activeLayoutIndex, fieldNumber: 1)
    }
    if !self.layouts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.layouts, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_PhysicalLayouts, rhs: Zmk_Keymap_PhysicalLayouts) -> Bool {
    if lhs.activeLayoutIndex != rhs.activeLayoutIndex {return false}
    if lhs.layouts != rhs.layouts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_PhysicalLayout: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PhysicalLayout"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}keys\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.keys) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.keys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.keys, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_PhysicalLayout, rhs: Zmk_Keymap_PhysicalLayout) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.keys != rhs.keys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Keymap_KeyPhysicalAttrs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeyPhysicalAttrs"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}width\0\u{1}height\0\u{1}x\0\u{1}y\0\u{1}r\0\u{1}rx\0\u{1}ry\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularSInt32Field(value: &self.width) }()
      case 2: try { try decoder.decodeSingularSInt32Field(value: &self.height) }()
      case 3: try { try decoder.decodeSingularSInt32Field(value: &self.x) }()
      case 4: try { try decoder.decodeSingularSInt32Field(value: &self.y) }()
      case 5: try { try decoder.decodeSingularSInt32Field(value: &self.r) }()
      case 6: try { try decoder.decodeSingularSInt32Field(value: &self.rx) }()
      case 7: try { try decoder.decodeSingularSInt32Field(value: &self.ry) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.width != 0 {
      try visitor.visitSingularSInt32Field(value: self.width, fieldNumber: 1)
    }
    if self.height != 0 {
      try visitor.visitSingularSInt32Field(value: self.height, fieldNumber: 2)
    }
    if self.x != 0 {
      try visitor.visitSingularSInt32Field(value: self.x, fieldNumber: 3)
    }
    if self.y != 0 {
      try visitor.visitSingularSInt32Field(value: self.y, fieldNumber: 4)
    }
    if self.r != 0 {
      try visitor.visitSingularSInt32Field(value: self.r, fieldNumber: 5)
    }
    if self.rx != 0 {
      try visitor.visitSingularSInt32Field(value: self.rx, fieldNumber: 6)
    }
    if self.ry != 0 {
      try visitor.visitSingularSInt32Field(value: self.ry, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Keymap_KeyPhysicalAttrs, rhs: Zmk_Keymap_KeyPhysicalAttrs) -> Bool {
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.x != rhs.x {return false}
    if lhs.y != rhs.y {return false}
    if lhs.r != rhs.r {return false}
    if lhs.rx != rhs.rx {return false}
    if lhs.ry != rhs.ry {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
