// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: meta.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated enum Zmk_Meta_ErrorConditions: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case generic // = 0
  case unlockRequired // = 1
  case rpcNotFound // = 2
  case msgDecodeFailed // = 3
  case msgEncodeFailed // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .generic
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .generic
    case 1: self = .unlockRequired
    case 2: self = .rpcNotFound
    case 3: self = .msgDecodeFailed
    case 4: self = .msgEncodeFailed
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .generic: return 0
    case .unlockRequired: return 1
    case .rpcNotFound: return 2
    case .msgDecodeFailed: return 3
    case .msgEncodeFailed: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Zmk_Meta_ErrorConditions] = [
    .generic,
    .unlockRequired,
    .rpcNotFound,
    .msgDecodeFailed,
    .msgEncodeFailed,
  ]

}

nonisolated struct Zmk_Meta_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var responseType: Zmk_Meta_Response.OneOf_ResponseType? = nil

  var noResponse: Bool {
    get {
      if case .noResponse(let v)? = responseType {return v}
      return false
    }
    set {responseType = .noResponse(newValue)}
  }

  var simpleError: Zmk_Meta_ErrorConditions {
    get {
      if case .simpleError(let v)? = responseType {return v}
      return .generic
    }
    set {responseType = .simpleError(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_ResponseType: Equatable, Sendable {
    case noResponse(Bool)
    case simpleError(Zmk_Meta_ErrorConditions)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "zmk.meta"

nonisolated extension Zmk_Meta_ErrorConditions: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GENERIC\0\u{1}UNLOCK_REQUIRED\0\u{1}RPC_NOT_FOUND\0\u{1}MSG_DECODE_FAILED\0\u{1}MSG_ENCODE_FAILED\0")
}

nonisolated extension Zmk_Meta_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}no_response\0\u{3}simple_error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .noResponse(v)
        }
      }()
      case 2: try {
        var v: Zmk_Meta_ErrorConditions?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.responseType != nil {try decoder.handleConflictingOneOf()}
          self.responseType = .simpleError(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.responseType {
    case .noResponse?: try {
      guard case .noResponse(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    }()
    case .simpleError?: try {
      guard case .simpleError(let v)? = self.responseType else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Meta_Response, rhs: Zmk_Meta_Response) -> Bool {
    if lhs.responseType != rhs.responseType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
