// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: studio.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Requests

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Zmk_Studio_Request: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt32 = 0

  var subsystem: Zmk_Studio_Request.OneOf_Subsystem? = nil

  var core: Zmk_Core_Request {
    get {
      if case .core(let v)? = subsystem {return v}
      return Zmk_Core_Request()
    }
    set {subsystem = .core(newValue)}
  }

  var behaviors: Zmk_Behaviors_Request {
    get {
      if case .behaviors(let v)? = subsystem {return v}
      return Zmk_Behaviors_Request()
    }
    set {subsystem = .behaviors(newValue)}
  }

  var keymap: Zmk_Keymap_Request {
    get {
      if case .keymap(let v)? = subsystem {return v}
      return Zmk_Keymap_Request()
    }
    set {subsystem = .keymap(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Subsystem: Equatable, Sendable {
    case core(Zmk_Core_Request)
    case behaviors(Zmk_Behaviors_Request)
    case keymap(Zmk_Keymap_Request)

  }

  init() {}
}

nonisolated struct Zmk_Studio_Response: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: Zmk_Studio_Response.OneOf_Type? = nil

  var requestResponse: Zmk_Studio_RequestResponse {
    get {
      if case .requestResponse(let v)? = type {return v}
      return Zmk_Studio_RequestResponse()
    }
    set {type = .requestResponse(newValue)}
  }

  var notification: Zmk_Studio_Notification {
    get {
      if case .notification(let v)? = type {return v}
      return Zmk_Studio_Notification()
    }
    set {type = .notification(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Type: Equatable, Sendable {
    case requestResponse(Zmk_Studio_RequestResponse)
    case notification(Zmk_Studio_Notification)

  }

  init() {}
}

nonisolated struct Zmk_Studio_RequestResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requestID: UInt32 = 0

  var subsystem: Zmk_Studio_RequestResponse.OneOf_Subsystem? = nil

  var meta: Zmk_Meta_Response {
    get {
      if case .meta(let v)? = subsystem {return v}
      return Zmk_Meta_Response()
    }
    set {subsystem = .meta(newValue)}
  }

  var core: Zmk_Core_Response {
    get {
      if case .core(let v)? = subsystem {return v}
      return Zmk_Core_Response()
    }
    set {subsystem = .core(newValue)}
  }

  var behaviors: Zmk_Behaviors_Response {
    get {
      if case .behaviors(let v)? = subsystem {return v}
      return Zmk_Behaviors_Response()
    }
    set {subsystem = .behaviors(newValue)}
  }

  var keymap: Zmk_Keymap_Response {
    get {
      if case .keymap(let v)? = subsystem {return v}
      return Zmk_Keymap_Response()
    }
    set {subsystem = .keymap(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Subsystem: Equatable, Sendable {
    case meta(Zmk_Meta_Response)
    case core(Zmk_Core_Response)
    case behaviors(Zmk_Behaviors_Response)
    case keymap(Zmk_Keymap_Response)

  }

  init() {}
}

nonisolated struct Zmk_Studio_Notification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var subsystem: Zmk_Studio_Notification.OneOf_Subsystem? = nil

  var core: Zmk_Core_Notification {
    get {
      if case .core(let v)? = subsystem {return v}
      return Zmk_Core_Notification()
    }
    set {subsystem = .core(newValue)}
  }

  var keymap: Zmk_Keymap_Notification {
    get {
      if case .keymap(let v)? = subsystem {return v}
      return Zmk_Keymap_Notification()
    }
    set {subsystem = .keymap(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Subsystem: Equatable, Sendable {
    case core(Zmk_Core_Notification)
    case keymap(Zmk_Keymap_Notification)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "zmk.studio"

nonisolated extension Zmk_Studio_Request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Request"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{2}\u{2}core\0\u{1}behaviors\0\u{1}keymap\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.requestID) }()
      case 3: try {
        var v: Zmk_Core_Request?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .core(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .core(v)
        }
      }()
      case 4: try {
        var v: Zmk_Behaviors_Request?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .behaviors(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .behaviors(v)
        }
      }()
      case 5: try {
        var v: Zmk_Keymap_Request?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .keymap(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .keymap(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt32Field(value: self.requestID, fieldNumber: 1)
    }
    switch self.subsystem {
    case .core?: try {
      guard case .core(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .behaviors?: try {
      guard case .behaviors(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .keymap?: try {
      guard case .keymap(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Studio_Request, rhs: Zmk_Studio_Request) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.subsystem != rhs.subsystem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Studio_Response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Response"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_response\0\u{1}notification\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Zmk_Studio_RequestResponse?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .requestResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .requestResponse(v)
        }
      }()
      case 2: try {
        var v: Zmk_Studio_Notification?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .notification(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .notification(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .requestResponse?: try {
      guard case .requestResponse(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .notification?: try {
      guard case .notification(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Studio_Response, rhs: Zmk_Studio_Response) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Studio_RequestResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RequestResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}meta\0\u{1}core\0\u{1}behaviors\0\u{1}keymap\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.requestID) }()
      case 2: try {
        var v: Zmk_Meta_Response?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .meta(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .meta(v)
        }
      }()
      case 3: try {
        var v: Zmk_Core_Response?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .core(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .core(v)
        }
      }()
      case 4: try {
        var v: Zmk_Behaviors_Response?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .behaviors(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .behaviors(v)
        }
      }()
      case 5: try {
        var v: Zmk_Keymap_Response?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .keymap(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .keymap(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.requestID != 0 {
      try visitor.visitSingularUInt32Field(value: self.requestID, fieldNumber: 1)
    }
    switch self.subsystem {
    case .meta?: try {
      guard case .meta(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .core?: try {
      guard case .core(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .behaviors?: try {
      guard case .behaviors(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .keymap?: try {
      guard case .keymap(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Studio_RequestResponse, rhs: Zmk_Studio_RequestResponse) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.subsystem != rhs.subsystem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Zmk_Studio_Notification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Notification"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}core\0\u{2}\u{3}keymap\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: Zmk_Core_Notification?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .core(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .core(v)
        }
      }()
      case 5: try {
        var v: Zmk_Keymap_Notification?
        var hadOneofValue = false
        if let current = self.subsystem {
          hadOneofValue = true
          if case .keymap(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.subsystem = .keymap(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.subsystem {
    case .core?: try {
      guard case .core(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .keymap?: try {
      guard case .keymap(let v)? = self.subsystem else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Zmk_Studio_Notification, rhs: Zmk_Studio_Notification) -> Bool {
    if lhs.subsystem != rhs.subsystem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
